import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Providers } from "./providers";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: {
    template: "%s | Piercing",
    default: "Piercing"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-png" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"></link>
      </head>
      <body
        className={`${inter.className} antialiased group`}
      >
        <Providers>
          <Toaster 
            position="top-right" 
            theme="light"
            richColors
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}
