import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: {
    template: "%s | IBanking",
    default: "IBanking"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/images/logo.svg" type="image/x-png" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"></link>
      </head>
      <body
        className={`${inter.className} antialiased group`}
      >
        <Toaster 
        position="bottom-center" 
        toastOptions={
          {
            success: {style: {border: '1px solid green'}},
            error: {style: {border: '1px solid red'}}
          }
        }/>
        {children}
      </body>
    </html>
  );
}
